encoding: utf-8

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            C10F18
email:            sallyiam00@gmail.com
tagline:          'A Jekyll theme'
description:      'Perfluorodecalin'
url:              /
baseurl:          /

author:
  name:           'Decalin'
  url:            https://c10f18.github.io/

paginate:         5

# Custom vars
version:          0.0.1
sidebar_home_link:  true

github:
  repo:           /



plugins: [jekyll-paginate]
