encoding: utf-8

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Perfluorodecalin
tagline:          'A Jekyll theme'
description:      '느슨해진 일상에 호흡기 달기'
url:              /
baseurl:          /

author:
  name:           'Decalin'
  url:            https://c10f18.github.io/

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           /



plugins: [jekyll-paginate]
